// quickstarts/app-frameworks/tanstack-start/standalone/src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { streamFlow } from 'genkit/beta/client';

// Set VITE_BARGAIN_CHEF_URL to point at a different backend.
const FLOW_URL =
  import.meta.env.VITE_BARGAIN_CHEF_URL ?? 'http://localhost:8080/bargainChefFlow';

interface RecipeIngredient {
  name?: string;
  quantity?: string;
  onSale?: boolean;
}
interface Recipe {
  title?: string;
  description?: string;
  servings?: number;
  ingredients?: RecipeIngredient[];
  steps?: string[];
}

export const Route = createFileRoute('/')({
  component: Home,
});

function Home() {
  const [craving, setCraving] = useState('something warm with chicken');
  const [recipe, setRecipe] = useState<Recipe | null>(null);
  const [isStreaming, setIsStreaming] = useState(false);

  async function generateRecipe(e: React.FormEvent) {
    e.preventDefault();
    if (!craving.trim()) return;
    setRecipe(null);
    setIsStreaming(true);
    try {
      const result = streamFlow({ url: FLOW_URL, input: { craving } });
      for await (const partial of result.stream) setRecipe(partial as Recipe);
      await result.output;
    } catch (err) {
      console.error('Failed to generate recipe', err);
    } finally {
      setIsStreaming(false);
    }
  }

  return (
    <main>
      <h1>Bargain Chef</h1>
      <p className="tagline">
        Tell me what you feel like eating and I&apos;ll suggest a recipe built
        around today&apos;s grocery deals.
      </p>
      <form className="prompt" onSubmit={generateRecipe}>
        <input
          type="text"
          value={craving}
          onChange={(e) => setCraving(e.target.value)}
          name="craving"
          disabled={isStreaming}
          placeholder="What are you in the mood for?"
        />
        <button type="submit" disabled={isStreaming}>
          {isStreaming ? 'Cooking…' : 'Suggest a recipe'}
        </button>
      </form>
      {recipe && (
        <article>
          {recipe.title && <h2>{recipe.title}</h2>}
          {recipe.description && <p className="description">{recipe.description}</p>}
          {recipe.servings && (
            <p className="serves">
              <strong>Serves:</strong> {recipe.servings}
            </p>
          )}
          {recipe.ingredients?.length ? (
            <>
              <h3>Ingredients</h3>
              <ul className="ingredients">
                {recipe.ingredients.map((ing, i) => (
                  <li key={i}>
                    {ing.quantity} {ing.name}
                    {ing.onSale && <span className="badge">on sale</span>}
                  </li>
                ))}
              </ul>
            </>
          ) : null}
          {recipe.steps?.length ? (
            <>
              <h3>Steps</h3>
              <ol className="steps">
                {recipe.steps.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ol>
            </>
          ) : null}
        </article>
      )}
    </main>
  );
}

// quickstarts/app-frameworks/sveltekit/standalone/src/routes/+page.svelte
<script lang="ts">
  import { streamFlow } from 'genkit/beta/client';

  // Set VITE_BARGAIN_CHEF_URL to point at a different backend.
  const FLOW_URL =
    import.meta.env.VITE_BARGAIN_CHEF_URL ?? 'http://localhost:8080/bargainChefFlow';

  interface RecipeIngredient {
    name?: string;
    quantity?: string;
    onSale?: boolean;
  }
  interface Recipe {
    title?: string;
    description?: string;
    servings?: number;
    ingredients?: RecipeIngredient[];
    steps?: string[];
  }

  let craving = $state('something warm with chicken');
  let recipe = $state<Recipe | null>(null);
  let isStreaming = $state(false);

  async function generateRecipe(e: Event) {
    e.preventDefault();
    if (!craving.trim()) return;
    recipe = null;
    isStreaming = true;
    try {
      const result = streamFlow({ url: FLOW_URL, input: { craving } });
      for await (const partial of result.stream) recipe = partial as Recipe;
      await result.output;
    } catch (err) {
      console.error('Failed to generate recipe', err);
    } finally {
      isStreaming = false;
    }
  }
</script>

<main>
  <h1>Bargain Chef</h1>
  <p class="tagline">Tell me what you feel like eating and I'll suggest a recipe built around today's grocery deals.</p>
  <form class="prompt" onsubmit={generateRecipe}>
    <input
      type="text"
      bind:value={craving}
      name="craving"
      placeholder="What are you in the mood for?"
      disabled={isStreaming}
    />
    <button type="submit" disabled={isStreaming}>
      {isStreaming ? 'Cooking…' : 'Suggest a recipe'}
    </button>
  </form>
  {#if recipe}
    <article>
      {#if recipe.title}<h2>{recipe.title}</h2>{/if}
      {#if recipe.description}<p class="description">{recipe.description}</p>{/if}
      {#if recipe.servings}<p class="serves"><strong>Serves:</strong> {recipe.servings}</p>{/if}
      {#if recipe.ingredients?.length}
        <h3>Ingredients</h3>
        <ul class="ingredients">
          {#each recipe.ingredients as ing}
            <li>{ing.quantity} {ing.name}{#if ing.onSale} <span class="badge">on sale</span>{/if}</li>
          {/each}
        </ul>
      {/if}
      {#if recipe.steps?.length}
        <h3>Steps</h3>
        <ol class="steps">{#each recipe.steps as step}<li>{step}</li>{/each}</ol>
      {/if}
    </article>
  {/if}
</main>

<style>
  :global(body) { font-family: -apple-system, sans-serif; color: #1a1a1a; background: #fafafa; margin: 0; }
  main { max-width: 640px; margin: 0 auto; padding: 3rem 1.5rem; }
  h1 { font-size: 2rem; margin: 0 0 0.25rem; }
  .tagline { color: #555; margin: 0 0 2rem; }
  .serves { color: #555; margin: 0; font-size: 0.95rem; }
  .prompt { display: flex; gap: 0.5rem; margin-bottom: 2.5rem; }
  .prompt input { flex: 1; font: inherit; padding: 0.75rem 1rem; border: 1px solid #d0d0d0; border-radius: 8px; }
  .prompt button { font: inherit; font-weight: 500; padding: 0.75rem 1.25rem; border: 0; border-radius: 8px; background: #1a1a1a; color: #fff; cursor: pointer; }
  .prompt button:disabled { background: #999; cursor: not-allowed; }
  article { background: #fff; border: 1px solid #e5e5e5; border-radius: 12px; padding: 1.5rem 1.75rem; }
  .badge { display: inline-block; margin-left: 0.4rem; padding: 0.05rem 0.5rem; font-size: 0.75rem; background: #e8f5e9; color: #2e7d32; border-radius: 999px; }
</style>
